<#
.SYNOPSIS
    Parses Business Central code coverage .dat files
.DESCRIPTION
    Reads and parses the code coverage output files generated by BC CodeCoverage exporters.
    Supports the standard format: ObjectType,ObjectID,LineNo,CoverageStatus,NoOfHits
#>

# Object type mapping from BC internal IDs to names
$script:ObjectTypeMap = @{
    1  = 'TableData'
    3  = 'Table'
    5  = 'Codeunit'
    6  = 'XMLport'
    7  = 'MenuSuite'
    8  = 'Page'
    9  = 'Query'
    14 = 'Report'
    22 = 'TableExtension'
    23 = 'PageExtension'
    35 = 'PageCustomization'
    37 = 'Enum'
    38 = 'EnumExtension'
    40 = 'Profile'
    42 = 'ControlAddIn'
    44 = 'PermissionSet'
    45 = 'PermissionSetExtension'
    46 = 'ReportExtension'
    47 = 'Interface'
}

# Coverage status mapping
$script:CoverageStatusMap = @{
    0 = 'Covered'
    1 = 'NotCovered'
    2 = 'PartiallyCovered'
}

<#
.SYNOPSIS
    Parses a BC code coverage .dat file
.PARAMETER Path
    Path to the .dat coverage file
.OUTPUTS
    Array of coverage entry objects with ObjectType, ObjectID, LineNo, CoverageStatus, Hits
#>
function Read-BCCoverageFile {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    if (-not (Test-Path $Path)) {
        throw "Coverage file not found: $Path"
    }

    $coverageEntries = @()
    
    # BC coverage files are UTF-16 encoded
    $content = Get-Content -Path $Path -Encoding Unicode -ErrorAction Stop
    
    foreach ($line in $content) {
        # Skip empty lines
        if ([string]::IsNullOrWhiteSpace($line)) {
            continue
        }
        
        # Parse CSV: ObjectType,ObjectID,LineNo,CoverageStatus,NoOfHits
        $parts = $line.Split(',')
        
        if ($parts.Count -ge 5) {
            $objectTypeId = [int]$parts[0]
            $objectId = [int]$parts[1]
            $lineNo = [int]$parts[2]
            $coverageStatus = [int]$parts[3]
            $hits = [int]$parts[4]
            
            $entry = [PSCustomObject]@{
                ObjectTypeId   = $objectTypeId
                ObjectType     = if ($script:ObjectTypeMap.ContainsKey($objectTypeId)) { 
                    $script:ObjectTypeMap[$objectTypeId] 
                } else { 
                    "Unknown_$objectTypeId" 
                }
                ObjectId       = $objectId
                LineNo         = $lineNo
                CoverageStatus = $coverageStatus
                CoverageStatusName = if ($script:CoverageStatusMap.ContainsKey($coverageStatus)) {
                    $script:CoverageStatusMap[$coverageStatus]
                } else {
                    "Unknown_$coverageStatus"
                }
                Hits           = $hits
                IsCovered      = ($coverageStatus -eq 0 -or $coverageStatus -eq 2)
            }
            
            $coverageEntries += $entry
        }
    }
    
    Write-Host "Parsed $($coverageEntries.Count) coverage entries from $Path"
    return $coverageEntries
}

<#
.SYNOPSIS
    Groups coverage entries by object (ObjectType + ObjectId)
.PARAMETER CoverageEntries
    Array of coverage entries from Read-BCCoverageFile
.OUTPUTS
    Hashtable keyed by "ObjectType.ObjectId" containing grouped entries
#>
function Group-CoverageByObject {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [array]$CoverageEntries
    )
    
    $grouped = @{}
    
    foreach ($entry in $CoverageEntries) {
        $key = "$($entry.ObjectType).$($entry.ObjectId)"
        
        if (-not $grouped.ContainsKey($key)) {
            $grouped[$key] = @{
                ObjectType   = $entry.ObjectType
                ObjectTypeId = $entry.ObjectTypeId
                ObjectId     = $entry.ObjectId
                Lines        = @()
            }
        }
        
        $grouped[$key].Lines += $entry
    }
    
    return $grouped
}

<#
.SYNOPSIS
    Calculates coverage statistics for a set of entries
.PARAMETER CoverageEntries
    Array of coverage entries
.OUTPUTS
    Object with TotalLines, CoveredLines, NotCoveredLines, CoveragePercent
#>
function Get-CoverageStatistics {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [array]$CoverageEntries
    )
    
    $totalLines = $CoverageEntries.Count
    $coveredLines = ($CoverageEntries | Where-Object { $_.IsCovered }).Count
    $notCoveredLines = $totalLines - $coveredLines
    $coveragePercent = if ($totalLines -gt 0) { 
        [math]::Round(($coveredLines / $totalLines) * 100, 2) 
    } else { 
        0 
    }
    
    return [PSCustomObject]@{
        TotalLines      = $totalLines
        CoveredLines    = $coveredLines
        NotCoveredLines = $notCoveredLines
        CoveragePercent = $coveragePercent
        LineRate        = if ($totalLines -gt 0) { $coveredLines / $totalLines } else { 0 }
    }
}

<#
.SYNOPSIS
    Gets the object type name from an ID
.PARAMETER ObjectTypeId
    The BC object type ID
.OUTPUTS
    String name of the object type
#>
function Get-ObjectTypeName {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [int]$ObjectTypeId
    )
    
    if ($script:ObjectTypeMap.ContainsKey($ObjectTypeId)) {
        return $script:ObjectTypeMap[$ObjectTypeId]
    }
    return "Unknown_$ObjectTypeId"
}

Export-ModuleMember -Function @(
    'Read-BCCoverageFile',
    'Group-CoverageByObject',
    'Get-CoverageStatistics',
    'Get-ObjectTypeName'
)
