name: Merge Code Coverage Summaries
author: Microsoft Corporation
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  coveragePath:
    description: Path containing downloaded coverage artifacts (each in a subfolder)
    required: true
  sourcePath:
    description: Path to the source code checkout (for app root path resolution)
    required: false
    default: ''
outputs:
  mergedCoverageFile:
    description: Path to the merged Cobertura XML file
    value: ${{ steps.merge.outputs.mergedCoverageFile }}
runs:
  using: composite
  steps:
    - name: run
      shell: ${{ inputs.shell }}
      id: merge
      env:
        _coveragePath: ${{ inputs.coveragePath }}
        _sourcePath: ${{ inputs.sourcePath }}
      run: |
        ${{ github.action_path }}/../Invoke-AlGoAction.ps1 -ActionName "MergeCoverageSummaries" -Action {
          ${{ github.action_path }}/MergeCoverageSummaries.ps1 -coveragePath $ENV:_coveragePath -sourcePath $ENV:_sourcePath
        }
branding:
  icon: bar-chart-2
  color: blue
